### ISSUE TITLE
 FAIL  src/components/App/App.test.tsx - TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by lancegliser** [lancegliser/react-apollo#1]
sr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js test --scripts-prepend-node-path=auto

> react-apollo@1.0.0 test
> react-scripts test
No tests found related to files changed since last commit.
Press `a` to run all tests, or run Jest with `--watchAll`.

Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press q to quit watch mode.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press Enter to trigger a test run.
 FAIL  src/components/App/App.test.tsx
  ✕ renders learn react link (112 ms)

  ● renders learn react link

    TypeError: Cannot read property 'add' of undefined

      4 |
      5 | test("renders learn react link", () => {
    > 6 |   const { getByText } = render(<App />);
        |                         ^
      7 |   const linkElement = getByText(/learn react/i);
      8 |   expect(linkElement).toBeInTheDocument();
      9 | });

      at e.r.init (node_modules/react-helmet-async/src/Dispatcher.js:8:41)
      at e.r.render (node_modules/react-helmet-async/src/Dispatcher.js:13:24)
      at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:17485:31)
      at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:17435:24)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19073:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23964:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22707:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:22670:7)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22293:18)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:22431:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:26020:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at node_modules/@testing-library/react/dist/pure.js:86:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (node_modules/@testing-library/react/dist/pure.js:82:26)
      at Object.<anonymous> (src/components/App/App.test.tsx:6:25)

  console.error
    Error: Uncaught [TypeError: Cannot read property 'add' of undefined]
        at reportException (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at innerInvokeEventListeners (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
        at invokeEventListeners (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
        at HTMLUnknownElementImpl._dispatch (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
        at HTMLUnknownElement.dispatchEvent (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
        at Object.invokeGuardedCallbackDev (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
        at invokeGuardedCallback (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
        at beginWork$1 (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:23964:7)
        at performUnitOfWork (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:22779:12) TypeError: Cannot read property 'add' of undefined
        at e.r.init (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-helmet-async/src/Dispatcher.js:8:41)
        at e.r.render (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-helmet-async/src/Dispatcher.js:13:24)
        at finishClassComponent (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:17485:31)
        at updateClassComponent (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:17435:24)
        at beginWork (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:19073:16)
        at HTMLUnknownElement.callCallback (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
        at HTMLUnknownElement.callTheUserObjectsOperation (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
        at innerInvokeEventListeners (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
        at invokeEventListeners (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
        at HTMLUnknownElementImpl._dispatch (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
        at HTMLUnknownElement.dispatchEvent (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
        at Object.invokeGuardedCallbackDev (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
        at invokeGuardedCallback (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
        at beginWork$1 (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:23964:7)
        at performUnitOfWork (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:22779:12)
        at workLoopSync (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:22707:5)
        at renderRootSync (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:22670:7)
        at performSyncWorkOnRoot (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:22293:18)
        at scheduleUpdateOnFiber (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:21881:7)
        at updateContainer (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:25482:3)
        at /Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:26021:7
        at unbatchedUpdates (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:22431:12)
        at legacyRenderSubtreeIntoContainer (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:26020:5)
        at Object.render (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:26103:10)
        at /Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/@testing-library/react/dist/pure.js:86:25
        at batchedUpdates$1 (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom.development.js:22380:12)
        at act (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
        at render (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/@testing-library/react/dist/pure.js:82:26)
        at Object.<anonymous> (/Users/lancegliser/Projects/lancegliser/react-apollo/src/components/App/App.test.tsx:6:25)
        at Promise.then.completed (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/utils.js:276:28)
        at new Promise (<anonymous>)
        at callAsyncCircusFn (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/utils.js:216:10)
        at _callCircusTest (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/run.js:212:40)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at _runTest (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/run.js:149:3)
        at _runTestsForDescribeBlock (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/run.js:63:9)
        at run (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/run.js:25:3)
        at runAndTransformResultsToJestFormat (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:176:21)
        at jestAdapter (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:109:19)
        at runTestInternal (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-runner/build/runTest.js:380:16)
        at runTest (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-runner/build/runTest.js:472:34)

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)

  console.error
    The above error occurred in the <HelmetDispatcher> component:
    
        at HelmetDispatcher (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-helmet-async/src/Dispatcher.js:17:3)
        at Helmet (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/react-helmet-async/src/index.js:62:3)
        at App
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-dom/cjs/react-dom.development.js:20085:23)
      at update.callback (node_modules/react-dom/cjs/react-dom.development.js:20118:5)
      at callCallback (node_modules/react-dom/cjs/react-dom.development.js:12318:12)
      at commitUpdateQueue (node_modules/react-dom/cjs/react-dom.development.js:12339:9)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:20736:11)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:23426:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)

**Comment by lancegliser** [comment]
Next error after previous:


expect(...).toBeInTheDocument is not a function
TypeError: expect(...).toBeInTheDocument is not a function
    at Object.<anonymous> (/Users/lancegliser/Projects/lancegliser/react-apollo/src/components/App/App.test.tsx:8:23)
    at Promise.then.completed (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/utils.js:276:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/utils.js:216:10)
    at _callCircusTest (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/run.js:212:40)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at _runTest (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/run.js:149:3)
    at _runTestsForDescribeBlock (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/run.js:63:9)
    at run (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:176:21)
    at jestAdapter (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:109:19)
    at runTestInternal (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-runner/build/runTest.js:380:16)
    at runTest (/Users/lancegliser/Projects/lancegliser/react-apollo/node_modules/jest-runner/build/runTest.js:472:34)
